mod 'r_boot',
  :git => 'https://h0tbird@github.com/h0tbird/puppet-r_boot.git'

mod 'dnsmasq',
  :git => 'https://h0tbird@github.com/h0tbird/puppet-dnsmasq.git'

mod 'nfs',
  :git => 'https://h0tbird@github.com/h0tbird/puppet-nfs.git'
