#!/bin/bash

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

[ "$WAIT_NETWORK" ] && {

  RETRIES=20

  echo '[Init] Waiting for the network...'

  while [ $RETRIES -gt 0 ]; do
    ip r 2> /dev/null | grep -q default && break
    sleep 1; RETRIES=$((RETRIES - 1))
  done

  [ $RETRIES -eq 0 ] && {
    echo '[Init] There is no network'
    exit 1
  }

  echo '[Init] A default gateway is present'
}

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

IP=`ip -o a | awk -F"[ /]" '/eth1/ {print $7}'`
echo "$IP $HOSTNAME" > /etc/hosts.conf

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
exec $*
