#!/bin/sh

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

[ "$WAIT_IFACE" ] && {

  RETRIES=20

  echo "[Init] Waiting for ${WAIT_IFACE} network..."

  while [ $RETRIES -gt 0 ]; do
    ip a l dev $WAIT_IFACE | grep -q inet && break
    sleep 1; RETRIES=$((RETRIES - 1))
  done

  [ $RETRIES -eq 0 ] && {
    echo "[Init] There is no ${WAIT_IFACE} network"
    exit 1
  }

  echo "[Init] Interface ${WAIT_IFACE} is present"
}

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'

IP=`ip -o a | awk -F"[ /]" '/eth1/ {print $7}'`
echo "$IP $HOSTNAME" > /etc/hosts.conf

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
exec $*
